### ISSUE TITLE
The plugin should generate a config file so I am able to change the hotkey of some functions.

### ISSUE THREAD

**Issue by chlorine03** [Animal42069/HousingHelper#1]
Hey. First of all, very nice plugin, I will say. Just let me explain my grievance with this function:

"While holding Left Alt, selected items will move to mouse position."

Now normally this would be a great idea; unfortunately, due to how the game works, I've encountered several issues with it.

The reason for this is that I tend to Alt Tab (with the LAlt key) to switch to another window, and if I'm editing something in the housing editor, the item will just snap to where my mouse position is, which is usually in the middle of nowhere, and I've found that this action cannot be reserved by pressing "Undo". This is an annoying but tolerable issue.

However, there is another much bigger problem with this function. I'm not sure why, but I suppose when the game loads into a save file, it enters housing mode to place the items that the user has built to their original location. Well, guess what? When I load the game I often switch to another window while it's loading (it's only natural right?), and this has caused countless issues with housing, particularly items blocking my way out so I can't access the housing editor to fix it, and I pretty much lost the third housing area in the Island of Ruins due to this feature.

Because of this, I believe that adding a simple config file that allows the user to change the hotkey of the function to something else would prove very useful.

I'm sorry if I sound imposing, but I really do like the plugin, it's just that one feature that's been causing me problems.

**Comment by Animal42069** [comment]
Resolved with 1.2.0
